version: '3.0'

services:
  nginx:
    build:
      context: ./docker/nginx
    container_name: pokemon-nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./codebase:/app
  php-fpm:
    build:
      context: ./docker/php-fpm
    container_name: pokemon-php-fpm
    volumes:
      - ./codebase:/app